// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package usermodel

import (
	"time"
)

type User struct {
	ID        int64     `json:"id"`
	Auth      int32     `json:"auth"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Pwd       string    `json:"pwd"`
	Departure string    `json:"departure"`
	Profile   string    `json:"profile"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
