// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package projectmodel

import (
	"time"
)

type Project struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Client    string    `json:"client"`
	Period    string    `json:"period"`
	Status    int32     `json:"status"`
	Markdown  string    `json:"markdown"`
	ManagerID int64     `json:"manager_id"`
	ShowCalc  int32     `json:"show_calc"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
