// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package projectmodel

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	DeleteProject(ctx context.Context, id int64) error
	GetProject(ctx context.Context, id int64) (*Project, error)
	ListCalcProjects(ctx context.Context) ([]*Project, error)
	ListProjectCalcsByManager(ctx context.Context, managerID int64) ([]*Project, error)
	ListProjects(ctx context.Context) ([]*Project, error)
	ListProjectsByManager(ctx context.Context, managerID int64) ([]*Project, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
