// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package jobmodel

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (sql.Result, error)
	DeleteJob(ctx context.Context, id int64) error
	GetJob(ctx context.Context, id int64) (*Job, error)
	ListCalcJobs(ctx context.Context) ([]*Job, error)
	ListJobs(ctx context.Context) ([]*Job, error)
	ListJobsByManager(ctx context.Context, managerID int64) ([]*Job, error)
	ListJobsCalcsByManager(ctx context.Context, managerID int64) ([]*Job, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (sql.Result, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
